version: '2'
services:
  smokeping:
    image: linuxserver/smokeping
    container_name: myping
    volumes:
      - /nfs/dcdata/smokeping/data:/data
      - /nfs/dcdata/smokeping/etc/:/config
    ports:
      - "8080:80" 
