version: '2'
services:
  myphp:
    image: php:7.2-fpm-alpine
    container_name: myphp
    volumes:
      - /nfs/dcdata/webapp/nginx/html:/var/www/html
      - /nfs/dcdata/webapp/php/etc:/usr/local/etc
    ports:
      - "9000:9000"
  nginx:
    image: nginx:alpine
    container_name: mynginx
    links: 
      - myphp
    volumes:
      - /nfs/dcdata/webapp/nginx/html:/usr/share/nginx/html
      - /nfs/dcdata/webapp/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - /nfs/dcdata/webapp/nginx/etc/conf.d:/etc/nginx/conf.d
      - /nfs/dcdata/webapp/nginx/log:/var/log/nginx
    ports:
      - "8000:80"
